package cmd

import (
	"encoding/yaml"
	"strings"
	"tool/cli"
	"tool/file"
)

App: Kust: {
	#var: apps: _
	for name, app in #var.apps {
		let DNE = "# Code generated by cue cmd kust-\(name). DO NOT EDIT\n"
		if app.alpha.kubernetes != _|_ {
			// generate kustomize manifests (shortcut)
			kust: _
			// generate kustomize manifests of specific app
			"kust-\(name)": {
				mkdir: file.Mkdir & {path: "resources"}
				printMkdir: cli.Print & {text: "Making directory \(mkdir.path)"}
				for _, resources in app.alpha.kubernetes.#resources for rname, resource in resources if resource.kind != "Secret" {
					let R = "\(resource.kind)_\(rname)"
					FC=(R): file.Create & {
						$after:   mkdir
						filename: "\(mkdir.path)/\(R)_gen.yaml"
						contents: strings.Join([DNE, yaml.Marshal(resource)], "\n")
					}
					"print-\(R)": cli.Print & {
						$after: printMkdir
						text:   "Generating \(FC.filename)"
					}
				}
				glob: file.Glob & {glob: "\(mkdir.path)/*.yaml"}
				kustomization: file.Create & {
					filename: "kustomization.yaml"
					contents: strings.Join([DNE, yaml.Marshal({resources: [for fn in glob.files {fn}]})], "\n")
				}
				printKust: cli.Print & {
					text: "(CAVEAT) \(kustomization.filename) might be stale, run again to refresh."
				}
			}
		}
	}
}
